import type { ModuleMeta } from './types'

export const modules: ModuleMeta[] = [
  {
    id: 'perusteet',
    title: 'Ensihoidon perusteet ja potilaan tutkiminen',
    shortTitle: 'Perusteet',
    description: 'ABCDE, kivun arviointi, kliiniset arviointityökalut ja potilasviestintä.',
    icon: 'ClipboardList',
    color: 'slate',
  },
  {
    id: 'hengitys',
    title: 'Hengitysvaikeus',
    shortTitle: 'Hengitys',
    description: 'Hengitysteiden fysiologia, astma/COPD, ilmarinta, keuhkoembolia ja muut hätätilat.',
    icon: 'Wind',
    color: 'sky',
  },
  {
    id: 'sydan',
    title: 'Sydän ja verenkierto',
    shortTitle: 'Sydän',
    description: 'Rintakipu, akuutti sepelvaltimotautikohtaus ja rytmihäiriöt.',
    icon: 'HeartPulse',
    color: 'rose',
  },
  {
    id: 'elvytys',
    title: 'Elvytys ja hengitystien varmistaminen',
    shortTitle: 'Elvytys',
    description: 'Sydänpysähdyspotilaan hoito, mekaaninen paineluelvytys, elvyttäen kuljetus ja anestesiaintubaatio.',
    icon: 'Zap',
    color: 'red',
  },
  {
    id: 'neurologia',
    title: 'Tajuttomuus ja äkillinen yleistilan heikkeneminen',
    shortTitle: 'Neurologia',
    description: 'Tajunnan häiriöiden mekanismit, tutkiminen ja pyörtymisen/yleistilan laskun erotusdiagnostiikka.',
    icon: 'Brain',
    color: 'violet',
  },
  {
    id: 'vatsa',
    title: 'Akuutti vatsa ja ruoansulatuskanavan verenvuoto',
    shortTitle: 'Vatsa',
    description: 'Vatsakivun mekanismit, hälyttävät löydökset ja GI-verenvuodon tunnistaminen.',
    icon: 'Stethoscope',
    color: 'amber',
  },
  {
    id: 'sokeri',
    title: 'Sokeritasapainon häiriöt',
    shortTitle: 'Sokeri',
    description: 'Hypoglykemia, hyperglykemia ja diabeettinen ketoasidoosi.',
    icon: 'Droplet',
    color: 'orange',
  },
  {
    id: 'myrkytys',
    title: 'Myrkytykset, päihteet ja mielenterveys',
    shortTitle: 'Myrkytykset',
    description: 'Intoksikaatiopotilaan hoito, alkoholin väärinkäyttö sekä mielenterveyden häiriöt ja kiihtynyt potilas.',
    icon: 'FlaskConical',
    color: 'emerald',
  },
  {
    id: 'trauma',
    title: 'Trauma',
    shortTitle: 'Trauma',
    description: 'Vammapotilaan tutkiminen ja eri vammamekanismien ensihoito.',
    icon: 'Bone',
    color: 'red',
  },
  {
    id: 'ymparisto',
    title: 'Ympäristöperäiset hätätilat',
    shortTitle: 'Ympäristö',
    description: 'Hypotermia ja hypoterminen elvytys, lämpöhalvaus sekä sukeltajantauti.',
    icon: 'Thermometer',
    color: 'cyan',
  },
  {
    id: 'lapset',
    title: 'Lapsipotilaan ensihoito',
    shortTitle: 'Lapset',
    description: 'Lapsen fysiologiset erityispiirteet ja tavallisimmat lasten hätätilanteet.',
    icon: 'Baby',
    color: 'pink',
  },
  {
    id: 'raskaus',
    title: 'Raskaana oleva ja synnyttäjä ensihoidossa',
    shortTitle: 'Raskaus',
    description: 'Raskausajan hätätilanteet ja synnytyksen kohtaaminen kentällä.',
    icon: 'Heart',
    color: 'fuchsia',
  },
  {
    id: 'infektiot',
    title: 'Infektiosairaudet',
    shortTitle: 'Infektiot',
    description: 'Sepsiksen tunnistaminen ja tavallisimmat infektioperäiset hätätilanteet.',
    icon: 'Bug',
    color: 'lime',
  },
  {
    id: 'geriatria',
    title: 'Ikääntynyt potilas',
    shortTitle: 'Ikääntyneet',
    description: 'Kaatuilu, gerastenia, huimaus, lääkehoito, infektiot ja muistisairaan kohtaaminen.',
    icon: 'PersonStanding',
    color: 'stone',
  },
  {
    id: 'laakkeet',
    title: 'Lääkehoito',
    shortTitle: 'Lääkkeet',
    description: 'Ensihoidon keskeisten lääkeaineiden pikaoppaat.',
    icon: 'Pill',
    color: 'teal',
  },
  {
    id: 'ammatillinen',
    title: 'Ensihoitajan ammatillinen osaaminen',
    shortTitle: 'Ammatillisuus',
    description: 'Ydinosaaminen, osaamisen kehittäminen ja täydennyskoulutus ensihoidossa.',
    icon: 'GraduationCap',
    color: 'indigo',
  },
]
